-- A-share policy + LLM analysis tables (migrated from MySQL).
-- Schema mirrors sentiment/services/scrapers/models.py with PG-native types.
-- Idempotent: safe to re-run.

CREATE TABLE IF NOT EXISTS policy_article (
    id              bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    source          varchar(50) NOT NULL,
    tier            integer NOT NULL,
    title           varchar(500) NOT NULL,
    url             varchar(500) NOT NULL UNIQUE,
    publish_date    date NOT NULL,
    category        varchar(100) NULL,
    summary         varchar(2000) NULL,
    content         text NULL,
    content_hash    varchar(64) NULL,
    scraped_at      timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at      timestamp with time zone NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_policy_article_source       ON policy_article (source);
CREATE INDEX IF NOT EXISTS idx_policy_article_publish_date ON policy_article (publish_date);
CREATE INDEX IF NOT EXISTS idx_policy_article_tier         ON policy_article (tier);

CREATE TABLE IF NOT EXISTS policy_analysis (
    id              bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    article_id      bigint NOT NULL,
    analysis_type   varchar(20) NOT NULL,
    industries      varchar(500) NULL,
    sentiment       double precision NULL,
    intensity       double precision NULL,
    impact_type     varchar(30) NULL,
    keywords_hit    varchar(500) NULL,
    summary_text    varchar(2000) NULL,
    -- Stored as jsonb for query-time extraction; migration accepts raw text.
    affected_stocks jsonb NULL,
    analyzed_at     timestamp with time zone NOT NULL DEFAULT NOW(),
    UNIQUE (article_id, analysis_type)
);

CREATE INDEX IF NOT EXISTS idx_policy_analysis_article ON policy_analysis (article_id);
CREATE INDEX IF NOT EXISTS idx_policy_analysis_type    ON policy_analysis (analysis_type);

-- scrape_log: keep MySQL parity for monitoring continuity.
CREATE TABLE IF NOT EXISTS scrape_log (
    id              bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    source          varchar(50) NOT NULL,
    started_at      timestamp with time zone NULL,
    finished_at     timestamp with time zone NULL,
    articles_found  integer NOT NULL DEFAULT 0,
    articles_new    integer NOT NULL DEFAULT 0,
    status          varchar(20) NOT NULL DEFAULT 'running',
    error_message   varchar(1000) NULL
);

CREATE INDEX IF NOT EXISTS idx_scrape_log_source ON scrape_log (source);
