-- A-share paper trading tables.
-- Idempotent: safe to re-run.

CREATE TABLE IF NOT EXISTS a_paper_account (
    id              bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_id      varchar(64) NOT NULL UNIQUE,
    initial_capital double precision NOT NULL,
    cash            double precision NOT NULL,
    created_at      timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at      timestamp with time zone NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS a_paper_position (
    id              bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_id      varchar(64) NOT NULL,
    ts_code         varchar(20) NOT NULL,
    shares          bigint NOT NULL,
    avg_cost        double precision NOT NULL,
    updated_at      timestamp with time zone NOT NULL DEFAULT NOW(),
    UNIQUE (account_id, ts_code)
);

CREATE INDEX IF NOT EXISTS idx_a_paper_position_account ON a_paper_position (account_id);

CREATE TABLE IF NOT EXISTS a_paper_trade (
    id              bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_id      varchar(64) NOT NULL,
    trade_date      date NOT NULL,
    ts_code         varchar(20) NOT NULL,
    side            varchar(8) NOT NULL,
    shares          bigint NOT NULL,
    price           double precision NOT NULL,
    gross           double precision NOT NULL,
    fees            double precision NOT NULL,
    created_at      timestamp with time zone NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_a_paper_trade_account_date ON a_paper_trade (account_id, trade_date);
CREATE INDEX IF NOT EXISTS idx_a_paper_trade_ts_code ON a_paper_trade (ts_code);
