-- ========================================================
-- A 股表 DDL — MySQL 版本 (drop + recreate)
-- 基于 migrate_ashare_schema.sql (PostgreSQL) 转换
-- !!! 执行前请备份数据库 !!!
-- ========================================================

-- 1. DROP 旧表
DROP TABLE IF EXISTS a_stock_basic;
DROP TABLE IF EXISTS a_daily_price;
DROP TABLE IF EXISTS a_index_daily;
DROP TABLE IF EXISTS a_financial_income;
DROP TABLE IF EXISTS a_financial_balance;
DROP TABLE IF EXISTS a_financial_cashflow;
DROP TABLE IF EXISTS a_financial_indicator;
DROP TABLE IF EXISTS a_industry_class;
DROP TABLE IF EXISTS a_macro_indicator;
DROP TABLE IF EXISTS a_commodity_price;
DROP TABLE IF EXISTS a_insider_transaction;
DROP TABLE IF EXISTS a_research_report;
DROP TABLE IF EXISTS a_trade_cal;
DROP TABLE IF EXISTS a_paper_account;
DROP TABLE IF EXISTS a_paper_position;
DROP TABLE IF EXISTS a_paper_trade;
DROP TABLE IF EXISTS a_industry_factor_config;
DROP TABLE IF EXISTS a_watchlist;
DROP TABLE IF EXISTS a_selection_result;
DROP TABLE IF EXISTS a_factor_snapshot;
DROP TABLE IF EXISTS import_progress;

-- 2. CREATE TABLE

CREATE TABLE a_stock_basic (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ts_code VARCHAR(20) NOT NULL,
  symbol VARCHAR(20) NULL,
  name VARCHAR(100) NULL,
  area VARCHAR(50) NULL,
  industry VARCHAR(100) NULL,
  fullname VARCHAR(200) NULL,
  enname VARCHAR(200) NULL,
  cnspell VARCHAR(50) NULL,
  market VARCHAR(50) NULL,
  exchange VARCHAR(20) NULL,
  curr_type VARCHAR(10) NULL,
  list_status VARCHAR(5) NULL,
  list_date DATE NULL,
  delist_date DATE NULL,
  is_hs VARCHAR(5) NULL,
  act_name VARCHAR(200) NULL,
  act_ent_type VARCHAR(100) NULL,
  is_st INT NOT NULL,
  board VARCHAR(20) NULL,
  total_share DOUBLE NULL,
  float_share DOUBLE NULL,
  free_share DOUBLE NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE a_daily_price (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ts_code VARCHAR(20) NOT NULL,
  trade_date DATE NOT NULL,
  `open` DOUBLE NULL,
  high DOUBLE NULL,
  low DOUBLE NULL,
  `close` DOUBLE NULL,
  pre_close DOUBLE NULL,
  `change` DOUBLE NULL,
  pct_chg DOUBLE NULL,
  vol DOUBLE NULL,
  amount DOUBLE NULL,
  turnover_rate DOUBLE NULL,
  turnover_rate_f DOUBLE NULL,
  volume_ratio DOUBLE NULL,
  pe DOUBLE NULL,
  pe_ttm DOUBLE NULL,
  pb DOUBLE NULL,
  ps DOUBLE NULL,
  ps_ttm DOUBLE NULL,
  dv_ratio DOUBLE NULL,
  dv_ttm DOUBLE NULL,
  total_share DOUBLE NULL,
  float_share DOUBLE NULL,
  free_share DOUBLE NULL,
  total_mv DOUBLE NULL,
  circ_mv DOUBLE NULL,
  adj_factor DOUBLE NULL,
  is_limit_up INT NOT NULL,
  is_limit_down INT NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE a_index_daily (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ts_code VARCHAR(20) NOT NULL,
  trade_date DATE NOT NULL,
  `close` DOUBLE NULL,
  `open` DOUBLE NULL,
  high DOUBLE NULL,
  low DOUBLE NULL,
  pre_close DOUBLE NULL,
  `change` DOUBLE NULL,
  pct_chg DOUBLE NULL,
  vol DOUBLE NULL,
  amount DOUBLE NULL,
  pe DOUBLE NULL,
  pb DOUBLE NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE a_financial_income (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ts_code VARCHAR(20) NOT NULL,
  ann_date DATE NULL,
  f_ann_date DATE NULL,
  end_date DATE NOT NULL,
  report_type VARCHAR(10) NULL,
  comp_type VARCHAR(10) NULL,
  end_type VARCHAR(10) NULL,
  basic_eps DOUBLE NULL,
  diluted_eps DOUBLE NULL,
  total_revenue DOUBLE NULL,
  revenue DOUBLE NULL,
  int_income DOUBLE NULL,
  prem_earned DOUBLE NULL,
  comm_income DOUBLE NULL,
  n_commis_income DOUBLE NULL,
  n_oth_income DOUBLE NULL,
  n_oth_b_income DOUBLE NULL,
  prem_income DOUBLE NULL,
  out_prem DOUBLE NULL,
  une_prem_reser DOUBLE NULL,
  reins_income DOUBLE NULL,
  n_sec_tb_income DOUBLE NULL,
  n_sec_uw_income DOUBLE NULL,
  n_asset_mg_income DOUBLE NULL,
  oth_b_income DOUBLE NULL,
  fv_value_chg_gain DOUBLE NULL,
  invest_income DOUBLE NULL,
  ass_invest_income DOUBLE NULL,
  forex_gain DOUBLE NULL,
  total_cogs DOUBLE NULL,
  oper_cost DOUBLE NULL,
  int_exp DOUBLE NULL,
  comm_exp DOUBLE NULL,
  biz_tax_surchg DOUBLE NULL,
  sell_exp DOUBLE NULL,
  admin_exp DOUBLE NULL,
  fin_exp DOUBLE NULL,
  assets_impair_loss DOUBLE NULL,
  prem_refund DOUBLE NULL,
  compens_payout DOUBLE NULL,
  reser_insur_liab DOUBLE NULL,
  div_payt DOUBLE NULL,
  reins_exp DOUBLE NULL,
  oper_exp DOUBLE NULL,
  compens_payout_refu DOUBLE NULL,
  insur_reser_refu DOUBLE NULL,
  reins_cost_refund DOUBLE NULL,
  other_bus_cost DOUBLE NULL,
  operate_profit DOUBLE NULL,
  non_oper_income DOUBLE NULL,
  non_oper_exp DOUBLE NULL,
  nca_disploss DOUBLE NULL,
  total_profit DOUBLE NULL,
  income_tax DOUBLE NULL,
  n_income DOUBLE NULL,
  n_income_attr_p DOUBLE NULL,
  minority_gain DOUBLE NULL,
  oth_compr_income DOUBLE NULL,
  t_compr_income DOUBLE NULL,
  compr_inc_attr_p DOUBLE NULL,
  compr_inc_attr_m_s DOUBLE NULL,
  ebit DOUBLE NULL,
  ebitda DOUBLE NULL,
  insurance_exp DOUBLE NULL,
  undist_profit DOUBLE NULL,
  distable_profit DOUBLE NULL,
  rd_exp DOUBLE NULL,
  fin_exp_int_exp DOUBLE NULL,
  fin_exp_int_inc DOUBLE NULL,
  transfer_surplus_rese DOUBLE NULL,
  transfer_housing_imprest DOUBLE NULL,
  transfer_oth DOUBLE NULL,
  adj_lossgain DOUBLE NULL,
  withdra_legal_surplus DOUBLE NULL,
  withdra_legal_pubfund DOUBLE NULL,
  withdra_biz_devfund DOUBLE NULL,
  withdra_rese_fund DOUBLE NULL,
  withdra_oth_ersu DOUBLE NULL,
  workers_welfare DOUBLE NULL,
  distr_profit_shrhder DOUBLE NULL,
  prfshare_payable_dvd DOUBLE NULL,
  comshare_payable_dvd DOUBLE NULL,
  capit_comstock_div DOUBLE NULL,
  net_after_nr_lp_correct DOUBLE NULL,
  credit_impa_loss DOUBLE NULL,
  net_expo_hedging_benefits DOUBLE NULL,
  oth_impair_loss_assets DOUBLE NULL,
  total_opcost DOUBLE NULL,
  amodcost_fin_assets DOUBLE NULL,
  oth_income DOUBLE NULL,
  asset_disp_income DOUBLE NULL,
  continued_net_profit DOUBLE NULL,
  end_net_profit DOUBLE NULL,
  update_flag VARCHAR(5) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE a_financial_balance (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ts_code VARCHAR(20) NOT NULL,
  ann_date DATE NULL,
  f_ann_date DATE NULL,
  end_date DATE NOT NULL,
  report_type VARCHAR(10) NULL,
  comp_type VARCHAR(10) NULL,
  end_type VARCHAR(10) NULL,
  total_share DOUBLE NULL,
  cap_rese DOUBLE NULL,
  undistr_porfit DOUBLE NULL,
  surplus_rese DOUBLE NULL,
  special_rese DOUBLE NULL,
  money_cap DOUBLE NULL,
  trad_asset DOUBLE NULL,
  notes_receiv DOUBLE NULL,
  accounts_receiv DOUBLE NULL,
  oth_receiv DOUBLE NULL,
  prepayment DOUBLE NULL,
  div_receiv DOUBLE NULL,
  int_receiv DOUBLE NULL,
  inventories DOUBLE NULL,
  amor_exp DOUBLE NULL,
  nca_within_1y DOUBLE NULL,
  sett_rsrv DOUBLE NULL,
  loanto_oth_bank_fi DOUBLE NULL,
  premium_receiv DOUBLE NULL,
  reinsur_receiv DOUBLE NULL,
  reinsur_res_receiv DOUBLE NULL,
  pur_resale_fa DOUBLE NULL,
  oth_cur_assets DOUBLE NULL,
  total_cur_assets DOUBLE NULL,
  fa_avail_for_sale DOUBLE NULL,
  htm_invest DOUBLE NULL,
  lt_eqt_invest DOUBLE NULL,
  invest_real_estate DOUBLE NULL,
  time_deposits DOUBLE NULL,
  oth_assets DOUBLE NULL,
  lt_rec DOUBLE NULL,
  fix_assets DOUBLE NULL,
  cip DOUBLE NULL,
  const_materials DOUBLE NULL,
  fixed_assets_disp DOUBLE NULL,
  produc_bio_assets DOUBLE NULL,
  oil_and_gas_assets DOUBLE NULL,
  intan_assets DOUBLE NULL,
  r_and_d DOUBLE NULL,
  goodwill DOUBLE NULL,
  lt_amor_exp DOUBLE NULL,
  defer_tax_assets DOUBLE NULL,
  decr_in_disbur DOUBLE NULL,
  oth_nca DOUBLE NULL,
  total_nca DOUBLE NULL,
  cash_reser_cb DOUBLE NULL,
  depos_in_oth_bfi DOUBLE NULL,
  prec_metals DOUBLE NULL,
  deriv_assets DOUBLE NULL,
  rr_reins_une_prem DOUBLE NULL,
  rr_reins_outstd_cla DOUBLE NULL,
  rr_reins_lins_liab DOUBLE NULL,
  rr_reins_lthins_liab DOUBLE NULL,
  refund_depos DOUBLE NULL,
  ph_pledge_loans DOUBLE NULL,
  refund_cap_depos DOUBLE NULL,
  indep_acct_assets DOUBLE NULL,
  client_depos DOUBLE NULL,
  client_prov DOUBLE NULL,
  transac_seat_fee DOUBLE NULL,
  invest_as_receiv DOUBLE NULL,
  total_assets DOUBLE NULL,
  lt_borr DOUBLE NULL,
  st_borr DOUBLE NULL,
  cb_borr DOUBLE NULL,
  depos_ib_deposits DOUBLE NULL,
  loan_oth_bank DOUBLE NULL,
  trading_fl DOUBLE NULL,
  notes_payable DOUBLE NULL,
  acct_payable DOUBLE NULL,
  adv_receipts DOUBLE NULL,
  sold_for_repur_fa DOUBLE NULL,
  comm_payable DOUBLE NULL,
  payroll_payable DOUBLE NULL,
  taxes_payable DOUBLE NULL,
  int_payable DOUBLE NULL,
  div_payable DOUBLE NULL,
  oth_payable DOUBLE NULL,
  acc_exp DOUBLE NULL,
  deferred_inc DOUBLE NULL,
  st_bonds_payable DOUBLE NULL,
  payable_to_reinsurer DOUBLE NULL,
  rsrv_insur_cont DOUBLE NULL,
  acting_trading_sec DOUBLE NULL,
  acting_uw_sec DOUBLE NULL,
  non_cur_liab_due_1y DOUBLE NULL,
  oth_cur_liab DOUBLE NULL,
  total_cur_liab DOUBLE NULL,
  bond_payable DOUBLE NULL,
  lt_payable DOUBLE NULL,
  specific_payables DOUBLE NULL,
  estimated_liab DOUBLE NULL,
  defer_tax_liab DOUBLE NULL,
  defer_inc_non_cur_liab DOUBLE NULL,
  oth_ncl DOUBLE NULL,
  total_ncl DOUBLE NULL,
  depos_oth_bfi DOUBLE NULL,
  deriv_liab DOUBLE NULL,
  depos DOUBLE NULL,
  agency_bus_liab DOUBLE NULL,
  oth_liab DOUBLE NULL,
  prem_receiv_adva DOUBLE NULL,
  depos_received DOUBLE NULL,
  ph_invest DOUBLE NULL,
  reser_une_prem DOUBLE NULL,
  reser_outstd_claims DOUBLE NULL,
  reser_lins_liab DOUBLE NULL,
  reser_lthins_liab DOUBLE NULL,
  indept_acc_liab DOUBLE NULL,
  pledge_borr DOUBLE NULL,
  indem_payable DOUBLE NULL,
  policy_div_payable DOUBLE NULL,
  total_liab DOUBLE NULL,
  treasury_share DOUBLE NULL,
  ordin_risk_reser DOUBLE NULL,
  forex_differ DOUBLE NULL,
  invest_loss_unconf DOUBLE NULL,
  minority_int DOUBLE NULL,
  total_hldr_eqy_exc_min_int DOUBLE NULL,
  total_hldr_eqy_inc_min_int DOUBLE NULL,
  total_liab_hldr_eqy DOUBLE NULL,
  lt_payroll_payable DOUBLE NULL,
  oth_comp_income DOUBLE NULL,
  oth_eqt_tools DOUBLE NULL,
  oth_eqt_tools_p_shr DOUBLE NULL,
  lending_funds DOUBLE NULL,
  acc_receivable DOUBLE NULL,
  st_fin_payable DOUBLE NULL,
  payables DOUBLE NULL,
  hfs_assets DOUBLE NULL,
  hfs_sales DOUBLE NULL,
  cost_fin_assets DOUBLE NULL,
  fair_value_fin_assets DOUBLE NULL,
  contract_assets DOUBLE NULL,
  contract_liab DOUBLE NULL,
  accounts_receiv_bill DOUBLE NULL,
  accounts_pay DOUBLE NULL,
  oth_rcv_total DOUBLE NULL,
  fix_assets_total DOUBLE NULL,
  cip_total DOUBLE NULL,
  oth_pay_total DOUBLE NULL,
  long_pay_total DOUBLE NULL,
  debt_invest DOUBLE NULL,
  oth_debt_invest DOUBLE NULL,
  oth_eq_invest DOUBLE NULL,
  oth_illiq_fin_assets DOUBLE NULL,
  oth_eq_ppbond DOUBLE NULL,
  receiv_financing DOUBLE NULL,
  use_right_assets DOUBLE NULL,
  lease_liab DOUBLE NULL,
  update_flag VARCHAR(5) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE a_financial_cashflow (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ts_code VARCHAR(20) NOT NULL,
  ann_date DATE NULL,
  f_ann_date DATE NULL,
  end_date DATE NOT NULL,
  comp_type VARCHAR(10) NULL,
  report_type VARCHAR(10) NULL,
  end_type VARCHAR(10) NULL,
  net_profit DOUBLE NULL,
  finan_exp DOUBLE NULL,
  c_fr_sale_sg DOUBLE NULL,
  recp_tax_rends DOUBLE NULL,
  n_depos_incr_fi DOUBLE NULL,
  n_incr_loans_cb DOUBLE NULL,
  n_inc_borr_oth_fi DOUBLE NULL,
  prem_fr_orig_contr DOUBLE NULL,
  n_incr_insured_dep DOUBLE NULL,
  n_reinsur_prem DOUBLE NULL,
  n_incr_disp_tfa DOUBLE NULL,
  ifc_cash_incr DOUBLE NULL,
  n_incr_disp_faas DOUBLE NULL,
  n_incr_loans_oth_bank DOUBLE NULL,
  n_cap_incr_repur DOUBLE NULL,
  c_fr_oth_operate_a DOUBLE NULL,
  c_inf_fr_operate_a DOUBLE NULL,
  c_paid_goods_s DOUBLE NULL,
  c_paid_to_for_empl DOUBLE NULL,
  c_paid_for_taxes DOUBLE NULL,
  n_incr_clt_loan_adv DOUBLE NULL,
  n_incr_dep_cbob DOUBLE NULL,
  c_pay_claims_orig_inco DOUBLE NULL,
  pay_handling_chrg DOUBLE NULL,
  pay_comm_insur_plcy DOUBLE NULL,
  oth_cash_pay_oper_act DOUBLE NULL,
  st_cash_out_act DOUBLE NULL,
  n_cashflow_act DOUBLE NULL,
  oth_recp_ral_inv_act DOUBLE NULL,
  c_disp_withdrwl_invest DOUBLE NULL,
  c_recp_return_invest DOUBLE NULL,
  n_recp_disp_fiolta DOUBLE NULL,
  n_recp_disp_sobu DOUBLE NULL,
  stot_inflows_inv_act DOUBLE NULL,
  c_pay_acq_const_fiolta DOUBLE NULL,
  c_paid_invest DOUBLE NULL,
  n_disp_subs_oth_biz DOUBLE NULL,
  oth_pay_ral_inv_act DOUBLE NULL,
  n_incr_pledge_loan DOUBLE NULL,
  stot_out_inv_act DOUBLE NULL,
  n_cashflow_inv_act DOUBLE NULL,
  c_recp_borrow DOUBLE NULL,
  proc_issue_bonds DOUBLE NULL,
  oth_cash_recp_ral_fnc_act DOUBLE NULL,
  stot_cash_in_fnc_act DOUBLE NULL,
  free_cashflow DOUBLE NULL,
  c_prepay_amt_borr DOUBLE NULL,
  c_pay_dist_dpcp_int_exp DOUBLE NULL,
  incl_dvd_profit_paid_sc_ms DOUBLE NULL,
  oth_cashpay_ral_fnc_act DOUBLE NULL,
  stot_cashout_fnc_act DOUBLE NULL,
  n_cash_flows_fnc_act DOUBLE NULL,
  eff_fx_flu_cash DOUBLE NULL,
  n_incr_cash_cash_equ DOUBLE NULL,
  c_cash_equ_beg_period DOUBLE NULL,
  c_cash_equ_end_period DOUBLE NULL,
  c_recp_cap_contrib DOUBLE NULL,
  incl_cash_rec_saims DOUBLE NULL,
  uncon_invest_loss DOUBLE NULL,
  prov_depr_assets DOUBLE NULL,
  depr_fa_coga_dpba DOUBLE NULL,
  amort_intang_assets DOUBLE NULL,
  lt_amort_deferred_exp DOUBLE NULL,
  decr_deferred_exp DOUBLE NULL,
  incr_acc_exp DOUBLE NULL,
  loss_disp_fiolta DOUBLE NULL,
  loss_scr_fa DOUBLE NULL,
  loss_fv_chg DOUBLE NULL,
  invest_loss DOUBLE NULL,
  decr_def_inc_tax_assets DOUBLE NULL,
  incr_def_inc_tax_liab DOUBLE NULL,
  decr_inventories DOUBLE NULL,
  decr_oper_payable DOUBLE NULL,
  incr_oper_payable DOUBLE NULL,
  others DOUBLE NULL,
  im_net_cashflow_oper_act DOUBLE NULL,
  conv_debt_into_cap DOUBLE NULL,
  conv_copbonds_due_within_1y DOUBLE NULL,
  fa_fnc_leases DOUBLE NULL,
  im_n_incr_cash_equ DOUBLE NULL,
  net_dism_capital_add DOUBLE NULL,
  net_cash_rece_sec DOUBLE NULL,
  credit_impa_loss DOUBLE NULL,
  use_right_asset_dep DOUBLE NULL,
  oth_loss_asset DOUBLE NULL,
  end_bal_cash DOUBLE NULL,
  beg_bal_cash DOUBLE NULL,
  end_bal_cash_equ DOUBLE NULL,
  beg_bal_cash_equ DOUBLE NULL,
  update_flag VARCHAR(5) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE a_financial_indicator (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ts_code VARCHAR(20) NOT NULL,
  ann_date DATE NULL,
  end_date DATE NOT NULL,
  eps DOUBLE NULL,
  dt_eps DOUBLE NULL,
  total_revenue_ps DOUBLE NULL,
  revenue_ps DOUBLE NULL,
  capital_rese_ps DOUBLE NULL,
  surplus_rese_ps DOUBLE NULL,
  undist_profit_ps DOUBLE NULL,
  extra_item DOUBLE NULL,
  profit_dedt DOUBLE NULL,
  gross_margin DOUBLE NULL,
  current_ratio DOUBLE NULL,
  quick_ratio DOUBLE NULL,
  cash_ratio DOUBLE NULL,
  invturn_days DOUBLE NULL,
  arturn_days DOUBLE NULL,
  inv_turn DOUBLE NULL,
  ar_turn DOUBLE NULL,
  ca_turn DOUBLE NULL,
  fa_turn DOUBLE NULL,
  assets_turn DOUBLE NULL,
  op_income DOUBLE NULL,
  valuechange_income DOUBLE NULL,
  interst_income DOUBLE NULL,
  daa DOUBLE NULL,
  ebit DOUBLE NULL,
  ebitda DOUBLE NULL,
  fcff DOUBLE NULL,
  fcfe DOUBLE NULL,
  current_exint DOUBLE NULL,
  noncurrent_exint DOUBLE NULL,
  interestdebt DOUBLE NULL,
  netdebt DOUBLE NULL,
  tangible_asset DOUBLE NULL,
  working_capital DOUBLE NULL,
  networking_capital DOUBLE NULL,
  invest_capital DOUBLE NULL,
  retained_earnings DOUBLE NULL,
  diluted2_eps DOUBLE NULL,
  bps DOUBLE NULL,
  ocfps DOUBLE NULL,
  retainedps DOUBLE NULL,
  cfps DOUBLE NULL,
  ebit_ps DOUBLE NULL,
  fcff_ps DOUBLE NULL,
  fcfe_ps DOUBLE NULL,
  netprofit_margin DOUBLE NULL,
  grossprofit_margin DOUBLE NULL,
  cogs_of_sales DOUBLE NULL,
  expense_of_sales DOUBLE NULL,
  profit_to_gr DOUBLE NULL,
  saleexp_to_gr DOUBLE NULL,
  adminexp_of_gr DOUBLE NULL,
  finaexp_of_gr DOUBLE NULL,
  impai_ttm DOUBLE NULL,
  gc_of_gr DOUBLE NULL,
  op_of_gr DOUBLE NULL,
  ebit_of_gr DOUBLE NULL,
  roe DOUBLE NULL,
  roe_waa DOUBLE NULL,
  roe_dt DOUBLE NULL,
  roa DOUBLE NULL,
  npta DOUBLE NULL,
  roic DOUBLE NULL,
  roe_yearly DOUBLE NULL,
  roa2_yearly DOUBLE NULL,
  roe_avg DOUBLE NULL,
  opincome_of_ebt DOUBLE NULL,
  investincome_of_ebt DOUBLE NULL,
  n_op_profit_of_ebt DOUBLE NULL,
  tax_to_ebt DOUBLE NULL,
  dtprofit_to_profit DOUBLE NULL,
  salescash_to_or DOUBLE NULL,
  ocf_to_or DOUBLE NULL,
  ocf_to_opincome DOUBLE NULL,
  capitalized_to_da DOUBLE NULL,
  debt_to_assets DOUBLE NULL,
  assets_to_eqt DOUBLE NULL,
  dp_assets_to_eqt DOUBLE NULL,
  ca_to_assets DOUBLE NULL,
  nca_to_assets DOUBLE NULL,
  tbassets_to_totalassets DOUBLE NULL,
  int_to_talcap DOUBLE NULL,
  eqt_to_talcapital DOUBLE NULL,
  currentdebt_to_debt DOUBLE NULL,
  longdeb_to_debt DOUBLE NULL,
  ocf_to_shortdebt DOUBLE NULL,
  debt_to_eqt DOUBLE NULL,
  eqt_to_debt DOUBLE NULL,
  eqt_to_interestdebt DOUBLE NULL,
  tangibleasset_to_debt DOUBLE NULL,
  tangasset_to_intdebt DOUBLE NULL,
  tangibleasset_to_netdebt DOUBLE NULL,
  ocf_to_debt DOUBLE NULL,
  ocf_to_interestdebt DOUBLE NULL,
  ocf_to_netdebt DOUBLE NULL,
  ebit_to_interest DOUBLE NULL,
  longdebt_to_workingcapital DOUBLE NULL,
  ebitda_to_debt DOUBLE NULL,
  turn_days DOUBLE NULL,
  roa_yearly DOUBLE NULL,
  roa_dp DOUBLE NULL,
  fixed_assets DOUBLE NULL,
  profit_prefin_exp DOUBLE NULL,
  non_op_profit DOUBLE NULL,
  op_to_ebt DOUBLE NULL,
  nop_to_ebt DOUBLE NULL,
  ocf_to_profit DOUBLE NULL,
  cash_to_liqdebt DOUBLE NULL,
  cash_to_liqdebt_withinterest DOUBLE NULL,
  op_to_liqdebt DOUBLE NULL,
  op_to_debt DOUBLE NULL,
  roic_yearly DOUBLE NULL,
  total_fa_trun DOUBLE NULL,
  profit_to_op DOUBLE NULL,
  q_opincome DOUBLE NULL,
  q_investincome DOUBLE NULL,
  q_dtprofit DOUBLE NULL,
  q_eps DOUBLE NULL,
  q_netprofit_margin DOUBLE NULL,
  q_gsprofit_margin DOUBLE NULL,
  q_exp_to_sales DOUBLE NULL,
  q_profit_to_gr DOUBLE NULL,
  q_saleexp_to_gr DOUBLE NULL,
  q_adminexp_to_gr DOUBLE NULL,
  q_finaexp_to_gr DOUBLE NULL,
  q_impair_to_gr_ttm DOUBLE NULL,
  q_gc_to_gr DOUBLE NULL,
  q_op_to_gr DOUBLE NULL,
  q_roe DOUBLE NULL,
  q_dt_roe DOUBLE NULL,
  q_npta DOUBLE NULL,
  q_opincome_to_ebt DOUBLE NULL,
  q_investincome_to_ebt DOUBLE NULL,
  q_dtprofit_to_profit DOUBLE NULL,
  q_salescash_to_or DOUBLE NULL,
  q_ocf_to_sales DOUBLE NULL,
  q_ocf_to_or DOUBLE NULL,
  basic_eps_yoy DOUBLE NULL,
  dt_eps_yoy DOUBLE NULL,
  cfps_yoy DOUBLE NULL,
  op_yoy DOUBLE NULL,
  ebt_yoy DOUBLE NULL,
  netprofit_yoy DOUBLE NULL,
  dt_netprofit_yoy DOUBLE NULL,
  ocf_yoy DOUBLE NULL,
  roe_yoy DOUBLE NULL,
  bps_yoy DOUBLE NULL,
  assets_yoy DOUBLE NULL,
  eqt_yoy DOUBLE NULL,
  tr_yoy DOUBLE NULL,
  or_yoy DOUBLE NULL,
  q_gr_yoy DOUBLE NULL,
  q_gr_qoq DOUBLE NULL,
  q_sales_yoy DOUBLE NULL,
  q_sales_qoq DOUBLE NULL,
  q_op_yoy DOUBLE NULL,
  q_op_qoq DOUBLE NULL,
  q_profit_yoy DOUBLE NULL,
  q_profit_qoq DOUBLE NULL,
  q_netprofit_yoy DOUBLE NULL,
  q_netprofit_qoq DOUBLE NULL,
  equity_yoy DOUBLE NULL,
  rd_exp DOUBLE NULL,
  update_flag VARCHAR(5) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE a_industry_class (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ts_code VARCHAR(20) NOT NULL,
  src VARCHAR(20) NOT NULL,
  level VARCHAR(5) NOT NULL,
  index_code VARCHAR(20) NULL,
  index_name VARCHAR(100) NULL,
  in_date DATE NULL,
  out_date DATE NULL,
  is_new VARCHAR(5) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE a_macro_indicator (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  indicator VARCHAR(50) NOT NULL,
  report_date DATE NOT NULL,
  freq VARCHAR(10) NOT NULL,
  value DOUBLE NULL,
  extra JSON NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE a_commodity_price (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ts_code VARCHAR(20) NOT NULL,
  name VARCHAR(50) NULL,
  trade_date DATE NOT NULL,
  pre_close DOUBLE NULL,
  pre_settle DOUBLE NULL,
  `open` DOUBLE NULL,
  high DOUBLE NULL,
  low DOUBLE NULL,
  `close` DOUBLE NULL,
  settle DOUBLE NULL,
  change1 DOUBLE NULL,
  change2 DOUBLE NULL,
  vol DOUBLE NULL,
  amount DOUBLE NULL,
  oi DOUBLE NULL,
  oi_chg DOUBLE NULL,
  delv_settle DOUBLE NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE a_insider_transaction (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ts_code VARCHAR(20) NOT NULL,
  name VARCHAR(100) NULL,
  change_date DATE NOT NULL,
  change_end_date DATE NULL,
  ann_date DATE NULL,
  holder_name VARCHAR(500) NOT NULL,
  holder_type VARCHAR(50) NULL,
  change_vol DOUBLE NULL,
  change_ratio DOUBLE NULL,
  hold_ratio DOUBLE NULL,
  total_share DOUBLE NULL,
  total_share_ratio DOUBLE NULL,
  float_share DOUBLE NULL,
  float_share_ratio DOUBLE NULL,
  latest_price DOUBLE NULL,
  change_pct DOUBLE NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE a_research_report (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  info_code VARCHAR(50) NOT NULL,
  ts_code VARCHAR(20) NULL,
  stock_code VARCHAR(20) NULL,
  stock_name VARCHAR(100) NULL,
  publish_date DATETIME NULL,
  title VARCHAR(500) NULL,
  `column` VARCHAR(50) NULL,
  `count` INT NULL,
  report_type VARCHAR(50) NULL,
  encode_url VARCHAR(500) NULL,
  market VARCHAR(20) NULL,
  org_code VARCHAR(50) NULL,
  org_name VARCHAR(200) NULL,
  org_s_name VARCHAR(200) NULL,
  org_type VARCHAR(50) NULL,
  researcher VARCHAR(500) NULL,
  author VARCHAR(500) NULL,
  author_id VARCHAR(200) NULL,
  em_rating_code VARCHAR(20) NULL,
  em_rating_name VARCHAR(50) NULL,
  em_rating_value DOUBLE NULL,
  rating_change VARCHAR(50) NULL,
  last_em_rating_code VARCHAR(20) NULL,
  last_em_rating_name VARCHAR(50) NULL,
  last_em_rating_value DOUBLE NULL,
  s_rating_code VARCHAR(20) NULL,
  s_rating_name VARCHAR(50) NULL,
  industry_code VARCHAR(50) NULL,
  industry_name VARCHAR(100) NULL,
  em_industry_code VARCHAR(50) NULL,
  indv_indu_code VARCHAR(50) NULL,
  indv_indu_name VARCHAR(100) NULL,
  indv_is_new VARCHAR(10) NULL,
  indv_aim_price_t DOUBLE NULL,
  indv_aim_price_l DOUBLE NULL,
  predict_this_year_eps DOUBLE NULL,
  predict_this_year_pe DOUBLE NULL,
  predict_next_year_eps DOUBLE NULL,
  predict_next_year_pe DOUBLE NULL,
  predict_next_two_year_eps DOUBLE NULL,
  predict_next_two_year_pe DOUBLE NULL,
  predict_last_year_eps DOUBLE NULL,
  predict_last_year_pe DOUBLE NULL,
  actual_last_year_eps DOUBLE NULL,
  actual_last_two_year_eps DOUBLE NULL,
  new_purchase_date VARCHAR(30) NULL,
  new_listing_date VARCHAR(30) NULL,
  new_issue_price DOUBLE NULL,
  new_pe_issue_a DOUBLE NULL,
  attach_type VARCHAR(20) NULL,
  attach_size VARCHAR(20) NULL,
  attach_pages VARCHAR(20) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE a_trade_cal (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  exchange VARCHAR(10) NOT NULL,
  cal_date DATE NOT NULL,
  is_open INT NOT NULL,
  pretrade_date DATE NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Paper trading tables (corrected to match Rust models: account_id, not account_name)

CREATE TABLE a_paper_account (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  account_id VARCHAR(50) NOT NULL,
  initial_capital DOUBLE NOT NULL,
  cash DOUBLE NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_a_paper_account_account_id (account_id)
);

CREATE TABLE a_paper_position (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  account_id VARCHAR(50) NOT NULL,
  ts_code VARCHAR(20) NOT NULL,
  shares BIGINT NOT NULL,
  avg_cost DOUBLE NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_a_paper_position_account_id_ts_code (account_id, ts_code)
);

CREATE TABLE a_paper_trade (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  account_id VARCHAR(50) NOT NULL,
  trade_date DATE NOT NULL,
  ts_code VARCHAR(20) NOT NULL,
  side VARCHAR(10) NOT NULL,
  shares BIGINT NOT NULL,
  price DOUBLE NOT NULL,
  gross DOUBLE NOT NULL,
  fees DOUBLE NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Import progress tracking (used by Tushare downloader)

CREATE TABLE import_progress (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  table_name VARCHAR(100) NOT NULL,
  ticker VARCHAR(50) NOT NULL,
  completed_at DATETIME NOT NULL,
  UNIQUE KEY uq_import_progress_table_ticker (table_name, ticker)
);

-- 3. UNIQUE INDEXES (对应 models Meta.unique_together)

CREATE UNIQUE INDEX uq_a_daily_price_ts_code_trade_date ON a_daily_price (ts_code, trade_date);
CREATE UNIQUE INDEX uq_a_index_daily_ts_code_trade_date ON a_index_daily (ts_code, trade_date);
CREATE UNIQUE INDEX uq_a_financial_income_ts_code_end_date_report_type ON a_financial_income (ts_code, end_date, report_type);
CREATE UNIQUE INDEX uq_a_financial_balance_ts_code_end_date_report_type ON a_financial_balance (ts_code, end_date, report_type);
CREATE UNIQUE INDEX uq_a_financial_cashflow_ts_code_end_date_report_type ON a_financial_cashflow (ts_code, end_date, report_type);
CREATE UNIQUE INDEX uq_a_financial_indicator_ts_code_end_date ON a_financial_indicator (ts_code, end_date);
CREATE UNIQUE INDEX uq_a_industry_class_ts_code_src_level_index_code_in_date ON a_industry_class (ts_code, src, level, index_code, in_date);
CREATE UNIQUE INDEX uq_a_macro_indicator_indicator_report_date_freq ON a_macro_indicator (indicator, report_date, freq);
CREATE UNIQUE INDEX uq_a_commodity_price_ts_code_trade_date ON a_commodity_price (ts_code, trade_date);
CREATE UNIQUE INDEX uq_a_insider_transaction_ts_code_change_date_holder_name_hol ON a_insider_transaction (ts_code, change_date, holder_name, holder_type);
CREATE UNIQUE INDEX uq_a_research_report_info_code ON a_research_report (info_code);
CREATE UNIQUE INDEX uq_a_trade_cal_exchange_cal_date ON a_trade_cal (exchange, cal_date);

-- 4. 查询加速索引

CREATE INDEX idx_a_daily_price_trade_date ON a_daily_price (trade_date);
CREATE INDEX idx_a_daily_price_ts_code ON a_daily_price (ts_code);
CREATE INDEX idx_a_index_daily_trade_date ON a_index_daily (trade_date);
CREATE INDEX idx_a_financial_income_ts_code_ann_date ON a_financial_income (ts_code, ann_date);
CREATE INDEX idx_a_financial_balance_ts_code_ann_date ON a_financial_balance (ts_code, ann_date);
CREATE INDEX idx_a_financial_cashflow_ts_code_ann_date ON a_financial_cashflow (ts_code, ann_date);
CREATE INDEX idx_a_financial_indicator_ts_code_ann_date ON a_financial_indicator (ts_code, ann_date);
CREATE INDEX idx_a_industry_class_index_code ON a_industry_class (index_code);
CREATE INDEX idx_a_macro_indicator_indicator_report_date ON a_macro_indicator (indicator, report_date);
CREATE INDEX idx_a_commodity_price_trade_date ON a_commodity_price (trade_date);
CREATE INDEX idx_a_insider_transaction_change_date ON a_insider_transaction (change_date);
CREATE INDEX idx_a_research_report_ts_code_publish_date ON a_research_report (ts_code, publish_date);
CREATE INDEX idx_a_trade_cal_cal_date ON a_trade_cal (cal_date);

-- 完成
