"""
US Stock Backtest Engine (position-based, T+0 execution)

Event-driven backtest framework for US equities:
    - Input: periodic stock selection signals (rebalance date -> target holdings + weights)
    - Execution: T+0 same-day close price, slippage only (zero commission), lot size = 1
    - No limit-up/down checks, no pending sells queue
    - Output: NAV curve, performance metrics, trade log

Execution model:
    - T+0: signals execute at same-day close price (adj_close)
    - Buy:  adj_close * (1 + slippage)
    - Sell: adj_close * (1 - slippage)
    - No minimum commission, no stamp tax
    - Lot size = 1 share (no 100-share constraint)
    - Cash tracking: sell first, then buy
    - Daily NAV = (cash + position market value) / initial capital
"""

import logging
from typing import Optional, Callable

import numpy as np
import pandas as pd
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

from services.config import (
    US_INITIAL_CAPITAL,
    US_BUY_COMMISSION,
    US_SELL_COMMISSION,
    US_STAMP_TAX,
    US_SLIPPAGE,
    US_USE_VOL_TARGETING,
    US_TARGET_VOL,
    US_VOL_LOOKBACK_DAYS,
    US_VOL_SCALE_MIN,
    US_VOL_SCALE_MAX,
    US_DD_START_THRESHOLD,
    US_DD_MAX_THRESHOLD,
    US_DD_MIN_POSITION,
    US_STRATEGY_MOM_WINDOW,
    US_STRATEGY_MOM_MIN_SCALE,
    US_SHORT_BORROW_FEE,
    US_SHORT_BORROW_FEE_TIERS,
    US_SHORT_STOP_LOSS,
    US_BENCHMARK_INDEX,
    LOG_LEVEL,
    PROJECT_ROOT,
)
from services.data.database import DatabaseManager

logger = logging.getLogger(__name__)
logger.setLevel(LOG_LEVEL)

plt.rcParams["font.sans-serif"] = ["Arial", "DejaVu Sans"]
plt.rcParams["axes.unicode_minus"] = False


class USBacktestEngine:
    """
    US Stock Backtest Engine (position-based, T+0 execution).

    Usage:
        engine = USBacktestEngine(db)
        result = engine.run(signals, start_date, end_date)
        engine.plot(result)
        print(engine.summary(result))
    """

    def __init__(
        self,
        db: DatabaseManager,
        buy_commission: float = US_BUY_COMMISSION,
        sell_commission: float = US_SELL_COMMISSION,
        stamp_tax: float = US_STAMP_TAX,
        slippage: float = US_SLIPPAGE,
        initial_capital: float = None,
        benchmark: str = US_BENCHMARK_INDEX,
        risk_controls: bool = True,
    ):
        self.db = db
        self.benchmark = benchmark
        self.initial_capital = initial_capital or US_INITIAL_CAPITAL

        self.buy_commission = buy_commission
        self.sell_commission = sell_commission
        self.stamp_tax = stamp_tax
        self.slippage = slippage
        self.risk_controls = risk_controls

    def run(
        self,
        signals: dict[str, pd.DataFrame],
        start_date: str,
        end_date: str,
        cancel_check: Optional[Callable[[], bool]] = None,
    ) -> dict:
        """
        Run US stock backtest (position-based, T+0 execution).

        Args:
            signals: {rebalance_date_str: DataFrame[ticker, weight]} dict.
                     Generated by USMultiFactorStrategy.generate_signals.
            start_date: Backtest start date (YYYY-MM-DD).
            end_date: Backtest end date (YYYY-MM-DD).
            cancel_check: Optional callable returning True to abort.

        Returns:
            Result dict with keys:
                - nav: Strategy NAV Series (DatetimeIndex)
                - benchmark_nav: S&P 500 benchmark NAV Series
                - trades: Trade log DataFrame
                - turnover: Per-period turnover DataFrame
                - stats: Performance statistics dict
        """
        logger.info(f"US backtest: {start_date} ~ {end_date}")

        def ensure_not_cancelled():
            if cancel_check and cancel_check():
                raise RuntimeError("Backtest cancelled")

        # Get all trade dates from S&P 500 index
        trade_dates = self._get_trade_dates(start_date, end_date)
        if trade_dates.empty:
            logger.error("No trade dates found in us_index_daily")
            return {}

        # Sort signal dates
        signal_dates = sorted(signals.keys())

        # Pre-load all relevant ticker prices
        all_tickers = set()
        for df_sig in signals.values():
            ensure_not_cancelled()
            all_tickers.update(df_sig["ticker"].tolist())
        all_tickers.discard("_INDEX_HEDGE")  # virtual ticker, handled separately
        price_cache = self._load_prices(list(all_tickers), start_date, end_date)

        # Load index prices for _INDEX_HEDGE (Russell 1000)
        idx_prices = self._load_index_prices(self.benchmark, start_date, end_date)
        # Inject into price_cache as _INDEX_HEDGE
        for date_str, px in idx_prices.items():
            price_cache[("_INDEX_HEDGE", date_str)] = {
                "open": px, "close": px, "adj_close": px, "volume": 1e9,
            }

        # Load market cap for tiered borrow fees
        mktcap_map = {}  # {ticker: market_cap}
        try:
            mktcap_df = self.db.query(
                "SELECT ticker, market_cap FROM us_stock_basic "
                "WHERE is_active = 1 AND market_cap IS NOT NULL"
            )
            if not mktcap_df.empty:
                mktcap_df["market_cap"] = pd.to_numeric(mktcap_df["market_cap"], errors="coerce")
                mktcap_map = dict(zip(mktcap_df["ticker"], mktcap_df["market_cap"]))
        except Exception as e:
            logger.debug(f"Backtest: failed to load mktcap for borrow fees: {e}")

        # Initialize portfolio state
        cash = float(self.initial_capital)
        positions = {}      # {ticker: float_shares}  (lot size = 1, can be fractional for splits)
        last_close = {}     # {ticker: float} for suspended/missing days
        short_entry_prices = {}  # {ticker: entry_price} for stop-loss tracking
        signal_idx = 0

        nav = pd.Series(dtype=float)
        trades = []
        turnover_list = []

        for i, today in enumerate(trade_dates):
            ensure_not_cancelled()

            today_str = today.strftime("%Y-%m-%d")
            day_turnover_amount = 0.0

            # === Check if today has a signal -> execute at today's close (T+0) ===
            if signal_idx < len(signal_dates) and today_str >= signal_dates[signal_idx]:
                new_signal = signals[signal_dates[signal_idx]]
                raw_weights = dict(
                    zip(new_signal["ticker"], new_signal["weight"])
                )

                # --- Risk control 1: Volatility targeting ---
                if self.risk_controls and US_USE_VOL_TARGETING and len(nav) >= US_VOL_LOOKBACK_DAYS + 1:
                    nav_arr = nav.values
                    recent_rets = (
                        np.diff(nav_arr[-US_VOL_LOOKBACK_DAYS - 1:])
                        / nav_arr[-US_VOL_LOOKBACK_DAYS - 1:-1]
                    )
                    realized_vol = np.std(recent_rets) * np.sqrt(252)
                    if realized_vol > 0:
                        vol_scale = np.clip(
                            US_TARGET_VOL / realized_vol,
                            US_VOL_SCALE_MIN,
                            US_VOL_SCALE_MAX,
                        )
                        if vol_scale < 1.0:
                            raw_weights = {
                                k: v * vol_scale for k, v in raw_weights.items()
                            }
                            logger.info(
                                f"Vol targeting: realized={realized_vol:.2%}, "
                                f"scale={vol_scale:.2f}"
                            )

                # --- Risk control 2: Linear drawdown response ---
                if self.risk_controls and len(nav) >= 5:
                    nav_arr = nav.values
                    peak = np.maximum.accumulate(nav_arr)
                    dd = (
                        abs((nav_arr[-1] - peak[-1]) / peak[-1])
                        if peak[-1] > 0
                        else 0
                    )
                    if dd >= US_DD_START_THRESHOLD:
                        if dd >= US_DD_MAX_THRESHOLD:
                            dd_scale = US_DD_MIN_POSITION
                        else:
                            dd_scale = 1.0 - (
                                (dd - US_DD_START_THRESHOLD)
                                / (US_DD_MAX_THRESHOLD - US_DD_START_THRESHOLD)
                                * (1.0 - US_DD_MIN_POSITION)
                            )
                        raw_weights = {
                            k: v * dd_scale for k, v in raw_weights.items()
                        }
                        logger.info(
                            f"Drawdown response: dd={dd:.2%}, scale={dd_scale:.2f}"
                        )

                # --- Risk control 3: Asymmetric strategy momentum filter ---
                if self.risk_controls and US_STRATEGY_MOM_WINDOW > 0 and len(nav) >= US_STRATEGY_MOM_WINDOW:
                    nav_arr = nav.values
                    nav_ma = np.mean(nav_arr[-US_STRATEGY_MOM_WINDOW:])
                    current_nav = nav_arr[-1]
                    if current_nav < nav_ma and nav_ma > 0:
                        short_window = min(20, len(nav_arr) - 1)
                        recent_ret = (
                            (nav_arr[-1] / nav_arr[-1 - short_window] - 1)
                            if nav_arr[-1 - short_window] > 0
                            else 0
                        )
                        if recent_ret < 0:
                            deviation = (nav_ma - current_nav) / nav_ma
                            mom_scale = max(
                                US_STRATEGY_MOM_MIN_SCALE, 1.0 - deviation * 2.5
                            )
                            raw_weights = {
                                k: v * mom_scale for k, v in raw_weights.items()
                            }
                            logger.info(
                                f"Strategy momentum filter: NAV={current_nav:.3f}, "
                                f"MA{US_STRATEGY_MOM_WINDOW}={nav_ma:.3f}, "
                                f"20d_ret={recent_ret:+.2%}, scale={mom_scale:.2f}"
                            )

                # === Execute T+0 at today's close ===
                target_weights = raw_weights

                # Estimate total portfolio value at today's close
                total_value = cash
                for ticker, shares in positions.items():
                    info = price_cache.get((ticker, today_str))
                    if info and info["adj_close"] and not pd.isna(info["adj_close"]):
                        px = info["adj_close"]
                    else:
                        px = last_close.get(ticker, 0)
                    total_value += shares * px

                # Calculate target shares and generate orders
                sell_orders = []   # (ticker, delta_shares, info)
                buy_orders = []    # (ticker, delta_shares, target_weight, info)

                all_involved = set(list(positions.keys()) + list(target_weights.keys()))

                for ticker in all_involved:
                    current_vol = positions.get(ticker, 0)
                    target_w = target_weights.get(ticker, 0)

                    info = price_cache.get((ticker, today_str))
                    if not info:
                        # No price data (halted/missing): keep current position
                        logger.debug(f"run: {ticker} 在 {today_str} 无价格数据（停牌/缺失），维持原仓位")
                        continue

                    close_px = info["adj_close"]
                    if not close_px or pd.isna(close_px) or close_px <= 0:
                        logger.debug(f"run: {ticker} 在 {today_str} 收盘价无效，跳过")
                        continue

                    target_vol = int(target_w * total_value / close_px)
                    delta = target_vol - current_vol

                    if abs(delta) < 1:
                        logger.debug(f"run: {ticker} 目标变动量 < 1 股，跳过")
                        continue

                    if delta < 0:
                        sell_orders.append((ticker, abs(delta), info))
                    else:
                        buy_orders.append((ticker, delta, target_w, info))

                # === Execute orders: close positions first, then open ===
                # Separate into: close/reduce orders first, then open/increase
                close_orders = []   # (ticker, delta, info) — reduce existing position toward target
                open_orders = []    # (ticker, delta, target_w, info) — open or increase position

                for ticker, volume, info in sell_orders:
                    cur = positions.get(ticker, 0)
                    if cur > 0:
                        # Closing/reducing long: sell actual shares
                        close_orders.append((ticker, -volume, info))
                    else:
                        # Opening/increasing short: short sell
                        open_orders.append((ticker, -volume, 0, info))

                for ticker, volume, weight, info in buy_orders:
                    cur = positions.get(ticker, 0)
                    if cur < 0:
                        # Covering short: buy to close
                        close_orders.append((ticker, volume, info))
                    else:
                        # Opening/increasing long: buy
                        open_orders.append((ticker, volume, weight, info))

                # Phase 1: Close/reduce positions (frees up cash)
                for ticker, delta, info in close_orders:
                    close_px = info["adj_close"]
                    cur = positions.get(ticker, 0)

                    if delta < 0:
                        # Selling long shares
                        sell_vol = min(abs(delta), abs(cur))
                        if sell_vol < 1:
                            logger.debug(f"run: {ticker} 平仓卖出量 < 1，跳过")
                            continue
                        exec_price = round(close_px * (1 - self.slippage), 4)
                        amount = sell_vol * exec_price
                        fees = self._calc_fees(amount, "SELL")
                        cash += amount - fees
                        day_turnover_amount += amount
                        positions[ticker] = cur + delta  # cur - sell_vol
                        direction = "SELL"
                    else:
                        # Buying to cover short
                        cover_vol = min(abs(delta), abs(cur))
                        if cover_vol < 1:
                            logger.debug(f"run: {ticker} 平仓买入量 < 1，跳过")
                            continue
                        exec_price = round(close_px * (1 + self.slippage), 4)
                        amount = cover_vol * exec_price
                        fees = self._calc_fees(amount, "BUY")
                        cash -= amount + fees
                        day_turnover_amount += amount
                        positions[ticker] = cur + cover_vol
                        direction = "COVER"

                    if positions.get(ticker, 0) == 0:
                        del positions[ticker]
                        short_entry_prices.pop(ticker, None)

                    trades.append({
                        "date": today_str, "ticker": ticker,
                        "direction": direction,
                        "volume": abs(delta),
                        "price": exec_price, "amount": amount, "fees": fees,
                    })

                # Phase 2: Open/increase positions
                # Sort: longs by weight desc, shorts by weight asc
                open_orders.sort(key=lambda x: x[2], reverse=True)

                for ticker, delta, weight, info in open_orders:
                    close_px = info["adj_close"]

                    if delta > 0:
                        # Buy long
                        exec_price = round(close_px * (1 + self.slippage), 4)
                        cost_per = exec_price * (1 + self.buy_commission)
                        max_affordable = int(cash / cost_per) if cost_per > 0 else 0
                        actual_vol = min(delta, max_affordable)
                        if actual_vol < 1:
                            logger.debug(f"run: {ticker} 买入量 < 1（资金不足或目标量过小），跳过")
                            continue
                        amount = actual_vol * exec_price
                        fees = self._calc_fees(amount, "BUY")
                        cash -= amount + fees
                        positions[ticker] = positions.get(ticker, 0) + actual_vol
                        direction = "BUY"
                    else:
                        # Short sell (delta < 0)
                        exec_price = round(close_px * (1 - self.slippage), 4)
                        short_vol = abs(delta)
                        amount = short_vol * exec_price
                        fees = self._calc_fees(amount, "SELL")
                        cash += amount - fees  # Short proceeds
                        positions[ticker] = positions.get(ticker, 0) - short_vol
                        actual_vol = short_vol
                        direction = "SHORT"
                        # Track entry price for stop-loss
                        if ticker not in short_entry_prices:
                            short_entry_prices[ticker] = exec_price

                    day_turnover_amount += amount
                    trades.append({
                        "date": today_str, "ticker": ticker,
                        "direction": direction,
                        "volume": actual_vol,
                        "price": exec_price, "amount": amount, "fees": fees,
                    })

                # Record turnover
                turnover = (
                    day_turnover_amount / total_value if total_value > 0 else 0
                )
                turnover_list.append(
                    {
                        "date": today_str,
                        "turnover": turnover / 2,  # single-side turnover
                    }
                )

                signal_idx += 1

            # === Daily borrow fee (tiered by market cap) + stop-loss for shorts ===
            stop_loss_tickers = []
            for ticker, shares in list(positions.items()):
                if shares >= 0:
                    continue
                px = last_close.get(ticker, 0)
                info = price_cache.get((ticker, today_str))
                if info and info["adj_close"] and not pd.isna(info["adj_close"]):
                    px = info["adj_close"]

                # Tiered borrow fee
                mcap = mktcap_map.get(ticker, 0)
                annual_rate = US_SHORT_BORROW_FEE  # default fallback
                for mcap_threshold, rate in sorted(
                    US_SHORT_BORROW_FEE_TIERS.items(), reverse=True
                ):
                    if mcap >= mcap_threshold:
                        annual_rate = rate
                        break
                borrow_cost = abs(shares) * px * (annual_rate / 252.0)
                cash -= borrow_cost

                # Stop-loss check: if price rose > threshold since entry
                entry_px = short_entry_prices.get(ticker)
                if entry_px and entry_px > 0 and px > 0:
                    loss_pct = (px / entry_px) - 1.0
                    if loss_pct >= US_SHORT_STOP_LOSS:
                        stop_loss_tickers.append((ticker, shares, px))

            # Execute stop-loss covers
            for ticker, shares, px in stop_loss_tickers:
                cover_vol = abs(shares)
                exec_price = round(px * (1 + self.slippage), 4)
                amount = cover_vol * exec_price
                fees = self._calc_fees(amount, "BUY")
                cash -= amount + fees
                entry_px = short_entry_prices.pop(ticker, 0)
                positions.pop(ticker, None)
                trades.append({
                    "date": today_str, "ticker": ticker,
                    "direction": "STOP_COVER",
                    "volume": cover_vol,
                    "price": exec_price, "amount": amount, "fees": fees,
                })
                logger.debug(
                    f"Short stop-loss: {ticker} covered at {exec_price:.2f} "
                    f"(entry={entry_px:.2f}, loss>={US_SHORT_STOP_LOSS:.0%})"
                )

            # === Daily NAV = (cash + position market value) / initial capital ===
            market_value = 0.0
            for ticker, shares in positions.items():
                info = price_cache.get((ticker, today_str))
                if (
                    info
                    and info["adj_close"]
                    and not pd.isna(info["adj_close"])
                ):
                    close_px = info["adj_close"]
                    last_close[ticker] = close_px
                else:
                    close_px = last_close.get(ticker, 0)
                market_value += shares * close_px

            nav[today] = (cash + market_value) / self.initial_capital

        # Load benchmark NAV
        benchmark_nav = self._get_benchmark_nav(start_date, end_date)

        # Compute stats
        stats = self._compute_stats(nav, benchmark_nav, trades, turnover_list)

        # FF5 alpha regression
        try:
            from services.strategy.ff5 import FF5Analyzer
            ff5 = FF5Analyzer()
            ff5_result = ff5.analyze(nav, freq="quarterly")
            if "full" in ff5_result:
                stats["ff5_alpha_annual"] = ff5_result["full"]["alpha_annualized"]
                stats["ff5_alpha_t_stat"] = ff5_result["full"]["alpha_t_stat"]
                stats["ff5_r_squared"] = ff5_result["full"]["r_squared"]
                stats["ff5_beta_mkt"] = ff5_result["full"]["betas"].get("Mkt-RF", 0)
                stats["ff5_beta_smb"] = ff5_result["full"]["betas"].get("SMB", 0)
                stats["ff5_beta_hml"] = ff5_result["full"]["betas"].get("HML", 0)
                stats["ff5_beta_rmw"] = ff5_result["full"]["betas"].get("RMW", 0)
                stats["ff5_beta_cma"] = ff5_result["full"]["betas"].get("CMA", 0)
        except Exception as e:
            logger.warning(f"FF5 analysis failed: {e}")

        result = {
            "nav": nav,
            "benchmark_nav": benchmark_nav,
            "trades": pd.DataFrame(trades),
            "turnover": pd.DataFrame(turnover_list),
            "stats": stats,
        }

        final_nav = nav.iloc[-1] if not nav.empty else 0
        logger.info(f"US backtest complete: final NAV={final_nav:.4f}")
        return result

    # ----------------------------------------------------------
    # Helper methods
    # ----------------------------------------------------------

    def _calc_fees(self, amount: float, direction: str) -> float:
        """
        Calculate transaction fees.

        US stocks: zero commission by default, slippage handled in exec price.
        Commission and stamp tax kept configurable for flexibility.

        Returns:
            Total fees (commission + stamp tax).
        """
        if direction == "BUY":
            return amount * self.buy_commission
        else:
            commission = amount * self.sell_commission
            stamp = amount * self.stamp_tax
            return commission + stamp

    def _get_trade_dates(self, start_date: str, end_date: str) -> pd.DatetimeIndex:
        """Get US trade dates from us_index_daily (^GSPC)."""
        df = self.db.query(
            "SELECT DISTINCT trade_date FROM us_index_daily "
            "WHERE index_code = :index_code "
            "AND trade_date >= :start_date "
            "AND trade_date <= :end_date "
            "ORDER BY trade_date",
            params={
                "index_code": self.benchmark,
                "start_date": start_date,
                "end_date": end_date,
            },
        )
        if df.empty:
            logger.debug("_get_trade_dates: 无交易日数据，返回空 DatetimeIndex")
            return pd.DatetimeIndex([])
        return pd.to_datetime(df["trade_date"])

    def _load_prices(
        self, tickers: list[str], start_date: str, end_date: str
    ) -> dict[tuple, dict]:
        """
        Pre-load price cache from us_daily_price.

        Returns:
            Dict {(ticker, date_str): {open, close, adj_close, high, low, volume}}.
        """
        if not tickers:
            logger.debug("_load_prices: ticker 列表为空，返回空缓存")
            return {}

        from services.factors.base import FactorBase

        params: dict = {"start_date": start_date, "end_date": end_date}
        in_clause, in_params = FactorBase._build_in_clause(tickers, prefix="tk")
        params.update(in_params)

        df = self.db.query(
            "SELECT ticker, trade_date, `open`, `close`, adj_close, "
            "`high`, `low`, volume "
            "FROM us_daily_price "
            "WHERE trade_date >= :start_date "
            "AND trade_date <= :end_date "
            f"AND ticker IN {in_clause}",
            params=params,
        )

        if df.empty:
            logger.warning("No price data loaded from us_daily_price")
            return {}

        df["trade_date"] = pd.to_datetime(df["trade_date"]).dt.strftime("%Y-%m-%d")
        # Fill missing adj_close with close
        df["adj_close"] = df["adj_close"].fillna(df["close"])
        df["open"] = df["open"].fillna(df["close"])
        df["high"] = df["high"].fillna(df["close"])
        df["low"] = df["low"].fillna(df["close"])

        cache = {}
        for row in df.itertuples(index=False):
            cache[(row.ticker, row.trade_date)] = {
                "open": row.open,
                "close": row.close,
                "adj_close": row.adj_close,
                "high": row.high,
                "low": row.low,
                "volume": row.volume,
            }

        logger.info(f"Price cache loaded: {len(cache)} entries for {len(tickers)} tickers")
        return cache

    def _load_index_prices(
        self, index_code: str, start_date: str, end_date: str
    ) -> dict[str, float]:
        """Load index daily close prices as {date_str: close}."""
        df = self.db.query(
            "SELECT trade_date, close FROM us_index_daily "
            "WHERE index_code = :idx AND trade_date >= :start AND trade_date <= :end "
            "ORDER BY trade_date",
            params={"idx": index_code, "start": start_date, "end": end_date},
        )
        if df.empty:
            logger.debug(f"_load_index_prices: {index_code} 无指数价格数据，返回空字典")
            return {}
        df["trade_date"] = pd.to_datetime(df["trade_date"]).dt.strftime("%Y-%m-%d")
        df["close"] = pd.to_numeric(df["close"], errors="coerce")
        return dict(zip(df["trade_date"], df["close"]))

    def _get_benchmark_nav(self, start_date: str, end_date: str) -> pd.Series:
        """
        Get S&P 500 benchmark NAV from us_index_daily.

        Returns:
            Benchmark NAV Series (DatetimeIndex), normalized to start at 1.0.
        """
        df = self.db.query(
            "SELECT trade_date, `close` FROM us_index_daily "
            "WHERE index_code = :index_code "
            "AND trade_date >= :start_date "
            "AND trade_date <= :end_date "
            "ORDER BY trade_date",
            params={
                "index_code": self.benchmark,
                "start_date": start_date,
                "end_date": end_date,
            },
        )

        if df.empty:
            logger.warning(
                f"No benchmark data for {self.benchmark}, "
                "returning empty Series"
            )
            return pd.Series(dtype=float)

        df["trade_date"] = pd.to_datetime(df["trade_date"])
        df = df.set_index("trade_date").sort_index()
        # Normalize to start at 1.0
        first_close = df["close"].iloc[0]
        if first_close and first_close > 0:
            df["nav"] = df["close"] / first_close
        else:
            df["nav"] = 1.0

        logger.info(f"Benchmark: {self.benchmark} ({len(df)} trade days)")
        return df["nav"]

    # ----------------------------------------------------------
    # Performance statistics
    # ----------------------------------------------------------

    @staticmethod
    def _compute_stats(
        nav: pd.Series,
        benchmark_nav: pd.Series,
        trades: list[dict],
        turnover_list: list[dict],
    ) -> dict:
        """
        Compute backtest performance statistics.

        Returns:
            Dict with: total_return, annual_return, max_drawdown, sharpe_ratio,
            calmar_ratio, win_rate, total_trades, annual_turnover, and
            benchmark comparison metrics.
        """
        if nav is None or nav.empty:
            logger.debug("_compute_stats: NAV 为空，返回空统计")
            return {}

        daily_ret = nav.pct_change().dropna()
        n_days = len(daily_ret)
        n_years = n_days / 252

        # Total return
        total_return = nav.iloc[-1] / nav.iloc[0] - 1

        # Annualized return
        annual_return = (
            (1 + total_return) ** (1 / max(n_years, 0.01)) - 1
        )

        # Annualized volatility
        annual_vol = daily_ret.std() * np.sqrt(252) if n_days > 1 else 0

        # Sharpe ratio (risk-free rate = 4% for US)
        rf = 0.04
        sharpe = (
            (annual_return - rf) / annual_vol if annual_vol > 0 else np.nan
        )

        # Maximum drawdown
        cummax = nav.cummax()
        drawdown = (nav - cummax) / cummax
        max_drawdown = drawdown.min()
        max_dd_date = drawdown.idxmin()

        # Calmar ratio
        calmar = (
            annual_return / abs(max_drawdown) if max_drawdown != 0 else np.nan
        )

        # Win rate (daily)
        win_rate = (daily_ret > 0).mean() if n_days > 0 else 0

        # Total trades
        total_trades = len(trades)

        # Average turnover
        avg_turnover = 0.0
        if turnover_list:
            avg_turnover = np.mean([t["turnover"] for t in turnover_list])

        # Annual turnover (avg single-side turnover * rebalance periods per year)
        n_rebalances = len(turnover_list)
        rebalances_per_year = n_rebalances / max(n_years, 0.01)
        annual_turnover = avg_turnover * rebalances_per_year

        stats = {
            "total_return": total_return,
            "annual_return": annual_return,
            "annual_volatility": annual_vol,
            "sharpe_ratio": sharpe,
            "max_drawdown": max_drawdown,
            "max_drawdown_date": (
                str(max_dd_date.date()) if pd.notna(max_dd_date) else ""
            ),
            "calmar_ratio": calmar,
            "win_rate": win_rate,
            "total_trades": total_trades,
            "avg_turnover": avg_turnover,
            "annual_turnover": annual_turnover,
            "trade_days": n_days,
        }

        # Benchmark comparison + capture ratios
        if benchmark_nav is not None and not benchmark_nav.empty:
            bm_ret = benchmark_nav.iloc[-1] / benchmark_nav.iloc[0] - 1
            bm_annual = (1 + bm_ret) ** (1 / max(n_years, 0.01)) - 1
            excess = annual_return - bm_annual
            stats["benchmark_total_return"] = bm_ret
            stats["benchmark_annual_return"] = bm_annual
            stats["excess_annual_return"] = excess

            # 月度下行/上行捕获率
            bm_monthly = benchmark_nav.resample("ME").last().pct_change().dropna()
            strat_monthly = nav.resample("ME").last().pct_change().dropna()
            common_idx = bm_monthly.index.intersection(strat_monthly.index)
            if len(common_idx) > 3:
                bm_m = bm_monthly.loc[common_idx]
                st_m = strat_monthly.loc[common_idx]

                # 下行捕获率：市场下跌月份，策略跌了多少
                down_months = bm_m < 0
                if down_months.sum() > 0:
                    down_capture = st_m[down_months].mean() / bm_m[down_months].mean()
                    stats["downside_capture"] = float(down_capture)

                # 上行捕获率：市场上涨月份，策略涨了多少
                up_months = bm_m > 0
                if up_months.sum() > 0:
                    up_capture = st_m[up_months].mean() / bm_m[up_months].mean()
                    stats["upside_capture"] = float(up_capture)

        return stats

    @staticmethod
    def summary(result: dict) -> pd.DataFrame:
        """
        Format backtest statistics into a readable DataFrame.

        Args:
            result: run() return value.

        Returns:
            Performance summary DataFrame with columns [Metric, Value].
        """
        stats = result.get("stats", {})
        if not stats:
            nav = result.get("nav")
            if nav is None or nav.empty:
                logger.debug("summary: NAV 为空，返回空 DataFrame")
                return pd.DataFrame()
            # Recompute if stats missing
            stats = USBacktestEngine._compute_stats(
                nav,
                result.get("benchmark_nav"),
                result.get("trades", pd.DataFrame()).to_dict("records")
                if isinstance(result.get("trades"), pd.DataFrame)
                else [],
                result.get("turnover", pd.DataFrame()).to_dict("records")
                if isinstance(result.get("turnover"), pd.DataFrame)
                else [],
            )

        metrics = {
            "Total Return": f"{stats.get('total_return', 0):.2%}",
            "Annual Return": f"{stats.get('annual_return', 0):.2%}",
            "Annual Volatility": f"{stats.get('annual_volatility', 0):.2%}",
            "Sharpe Ratio": f"{stats.get('sharpe_ratio', 0):.2f}",
            "Max Drawdown": f"{stats.get('max_drawdown', 0):.2%}",
            "Max Drawdown Date": stats.get("max_drawdown_date", ""),
            "Calmar Ratio": f"{stats.get('calmar_ratio', 0):.2f}",
            "Daily Win Rate": f"{stats.get('win_rate', 0):.2%}",
            "Total Trades": stats.get("total_trades", 0),
            "Avg Turnover": f"{stats.get('avg_turnover', 0):.2%}",
            "Annual Turnover": f"{stats.get('annual_turnover', 0):.2%}",
            "Trade Days": stats.get("trade_days", 0),
        }

        # Benchmark comparison
        if "benchmark_annual_return" in stats:
            metrics["Benchmark Annual Return"] = (
                f"{stats['benchmark_annual_return']:.2%}"
            )
            metrics["Excess Annual Return"] = (
                f"{stats.get('excess_annual_return', 0):.2%}"
            )

        return pd.DataFrame(
            list(metrics.items()), columns=["Metric", "Value"]
        )

    # ----------------------------------------------------------
    # Visualization
    # ----------------------------------------------------------

    @staticmethod
    def plot(result: dict, save_path: Optional[str] = None):
        """
        Plot NAV curve and drawdown chart.

        Args:
            result: run() return value.
            save_path: Path to save the chart image.
        """
        nav = result.get("nav")
        if nav is None or nav.empty:
            logger.debug("plot: NAV 为空，跳过绘图")
            return

        benchmark = result.get("benchmark_nav")

        fig, (ax1, ax2) = plt.subplots(
            2,
            1,
            figsize=(14, 8),
            gridspec_kw={"height_ratios": [3, 1]},
            sharex=True,
        )

        # NAV curve
        ax1.plot(
            nav.index, nav, label="Strategy", color="#e74c3c", linewidth=1.5
        )

        if benchmark is not None and not benchmark.empty:
            common_dates = nav.index.intersection(benchmark.index)
            if len(common_dates) > 0:
                bm_aligned = benchmark.loc[common_dates]
                bm_aligned = bm_aligned / bm_aligned.iloc[0] * nav.iloc[0]
                ax1.plot(
                    common_dates,
                    bm_aligned,
                    label=f"S&P 500",
                    color="#3498db",
                    linewidth=1.5,
                    alpha=0.7,
                )

        ax1.set_ylabel("NAV")
        ax1.set_title("US Stock Backtest Result")
        ax1.legend(loc="upper left")
        ax1.grid(True, alpha=0.3)

        # Drawdown curve
        cummax = nav.cummax()
        drawdown = (nav - cummax) / cummax
        ax2.fill_between(
            drawdown.index, 0, drawdown, color="#e74c3c", alpha=0.3
        )
        ax2.plot(drawdown.index, drawdown, color="#e74c3c", linewidth=0.8)
        ax2.set_ylabel("Drawdown")
        ax2.set_xlabel("Date")
        ax2.grid(True, alpha=0.3)

        plt.tight_layout()

        if save_path is None:
            output_dir = PROJECT_ROOT / "output"
            output_dir.mkdir(exist_ok=True)
            save_path = str(output_dir / "us_backtest_result.png")

        plt.savefig(save_path, dpi=150, bbox_inches="tight")
        plt.close()
        logger.info(f"Backtest chart saved: {save_path}")
